[package]
name = "quic-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = { version = "2.0.1" }
quinn = "0.11.9"
rcgen = "0.14.5"
tokio = { version = "1.48.0", features = ["full"] }
